# redis-server.yml
version: '3.7'
services:
  dbbackup:
    build: .
    container_name: dbbackup
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      #백업파일
      - ./backups:/root/backups
    # command: python3 main.py
    restart: unless-stopped
    working_dir: /usr/src/app
    privileged: true
    network_mode: host
    environment:
      - POSTGRES_USER=nothing
      - POSTGRES_PASSWORD=nothing
      - POSTGRES_DB_NAME=nothing
      - TZ=Asia/Seoul
